### ISSUE TITLE
Screenshots? Demos?

### ISSUE THREAD

**Issue by jwrunner** [kent-rasmussen/azt#36]
Hey, I have interests in building a simple tone charting web component that uses a Python library brought into Javascript via WASM, but haven't built it yet.

Your repo caught my eye in the July newsletter and I wanted to ask if you had any screenshots or video demos that you could post on the repo to help those browsing more easily understand what you've built? Thanks!

**Comment by kent-rasmussen** [comment]
Sorry, I'm missing the reference; which newsletter?

**Comment by jwrunner** [comment]
LingBits

**Comment by kent-rasmussen** [comment]
In short, no. The UI has changed frequently enough that I don't see documenting it as of today as worth it, yet. That may change before long. VBH is working on video demos, and another team was working on something, but again I'm trying to get functionality added to a 1.0 level (i.e., consonants, vowels, and tone) before spending too much time documenting what the tool looks like today.
